Fix broken build because of issues between OpenJDK and maven surefire and filesafe plugins
At the moment, the build breaks with the following error message:

org.apache.maven.surefire.booter.SurefireBooterForkException: The forked
VM terminated without properly saying goodbye

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911925 and
https://issues.apache.org/jira/browse/SUREFIRE-1588 for more information

The current solution is to set the useSystemClassLoader property of
surefire and failsafe plugins to false